<a href="https://colab.research.google.com/github/SunkaraboinaPraveenKumar/Machine_Learning_Projects/blob/main/NLPLanguageDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import string
import re
import codecs
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import feature_extraction
from sklearn import linear_model
from sklearn import pipeline
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [8]:
df=pd.read_csv("/content/Language Detection.csv")

In [9]:
df.head()

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [11]:
# Create separate DataFrames for each language
english_df = df[df['Language'] == "English"]
malayalam_df = df[df['Language'] == "Malayalam"]
hindi_df = df[df['Language'] == "Hindi"]
tamil_df = df[df['Language'] == "Tamil"]
kannada_df = df[df['Language'] == "Kannada"]
french_df = df[df['Language'] == "French"]
spanish_df = df[df['Language'] == "Spanish"]
portuguese_df = df[df['Language'] == "Portuguese"]
italian_df = df[df['Language'] == "Italian"]
russian_df = df[df['Language'] == "Russian"]
swedish_df = df[df['Language'] == "Sweedish"]  # Assuming you meant "Swedish" and there was a typo
dutch_df = df[df['Language'] == "Dutch"]
arabic_df = df[df['Language'] == "Arabic"]
turkish_df = df[df['Language'] == "Turkish"]
german_df = df[df['Language'] == "German"]
danish_df = df[df['Language'] == "Danish"]
greek_df = df[df['Language'] == "Greek"]

In [12]:
# Example: Show the first few rows of the German DataFrame
print(german_df.head())

                                                   Text Language
9498  .Wir sind alle auf der Suche nach schnellen We...   German
9499  Ich weiß, ich verstehe, was passiert, ist, das...   German
9500                          Wie wäre es also mit uns?   German
9501  Lernen Sie einige intelligente neue englische ...   German
9502  Also werden wir heute 10 neue intelligente Wör...   German


In [13]:
for char in string.punctuation:
  print(char,end="")
translate_table=dict((ord(char),None)for char in string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [14]:
# Define a function to process the text
def process_text(df, lang_name):
    data_lang = []
    lang_lang = []
    for i, line in df.iterrows():
        line = line['Text']  # Assuming the text is in the 'Text' column
        if len(line) != 0:
            line = line.lower()
            line = re.sub(r"\d+", "", line)
            line = line.translate(translate_table)
            data_lang.append(line)
            lang_lang.append(lang_name)
    return data_lang, lang_lang

In [33]:
# Process the text for each language
data_english, lang_english = process_text(english_df, "English")
data_malayalam, lang_malayalam = process_text(malayalam_df, "Malayalam")
data_hindi, lang_hindi = process_text(hindi_df, "Hindi")
data_tamil, lang_tamil = process_text(tamil_df, "Tamil")
data_kannada, lang_kannada = process_text(kannada_df, "Kannada")
data_french, lang_french = process_text(french_df, "French")
data_spanish, lang_spanish = process_text(spanish_df, "Spanish")
data_portuguese, lang_portuguese = process_text(portuguese_df, "Portuguese")
data_italian, lang_italian = process_text(italian_df, "Italian")
data_russian, lang_russian = process_text(russian_df, "Russian")
data_swedish, lang_swedish = process_text(swedish_df, "Swedish")
data_dutch, lang_dutch = process_text(dutch_df, "Dutch")
data_arabic, lang_arabic = process_text(arabic_df, "Arabic")
data_turkish, lang_turkish = process_text(turkish_df, "Turkish")
data_german, lang_german = process_text(german_df, "German")
data_danish, lang_danish = process_text(danish_df, "Danish")
data_greek, lang_greek = process_text(greek_df, "Greek")

# Example: Print processed English data
print(data_greek[:5])


['δεν υπάρχει αυτή τη στιγμή  λήμμα με αυτόν τον τίτλο', 'αν περιμένατε να βρίσκεται εδώ μια σελίδα και δεν υπάρχει η σελίδα μπορεί να μην εμφανίζεται λόγω καθυστέρησης στην ανανέωση της βάσης δεδομένων ή μπορεί να έχει διαγραφεί', 'δείτε την γρήγορη διαγραφή σελίδων για πιθανούς λόγους', 'μπορείτε να δοκιμάστε την λειτουργία εκκαθάρισης και να ελέγξετε το αρχείο διαγραφών', 'η βικιπαίδεια αγγλικά wikipedia γουικιπίντια είναι διεθνής παγκόσμια ψηφιακή διαδικτυακή ελεύθερου περιεχομένου εγκυκλοπαίδεια που βασίζεται σε ένα μοντέλο ανοικτό στη σύνταξη του περιεχομένου της']


In [17]:
x,y=df.iloc[:,0],df.iloc[:,1]
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(8269,)
(2068,)
(8269,)
(2068,)


In [20]:
#vectorizer
vectorizer=feature_extraction.text.TfidfVectorizer(ngram_range=(1,3),analyzer='char')
#uni,bi and tri grams

In [21]:
pipe_lr_r13=pipeline.Pipeline([
    ('vectorizer',vectorizer),
    ('clf',linear_model.LogisticRegression())
])

In [22]:
pipe_lr_r13.fit(X_train,Y_train)

Pipeline(steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char', ngram_range=(1, 3))),
                ('clf', LogisticRegression())])

In [23]:
y_predicted=pipe_lr_r13.predict(X_test)

In [24]:
acc=(metrics.accuracy_score(Y_test,y_predicted))*100
print(acc,'%')

98.25918762088975 %


In [25]:
matrix=metrics.confusion_matrix(Y_test,y_predicted)
print('Confusion Matrix: \n',matrix)

Confusion Matrix: 
 [[117   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  72   0   2   0   0   0   0   0   0   0   0   0   0   3   0   0]
 [  0   1 103   2   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   1 256   1   0   0   0   1   0   0   0   0   1   0   0   0]
 [  0   0   0   1 194   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2   3   0   0 100   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  70   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 145   0   0   3   0   4   0   0   0]
 [  0   0   0   0   0   0   0   0   0  77   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 114   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0 149   0   1   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0 142   0   0   0   0]
 [  0   0   0   0   0   0   0   0   2   0   0   1   1 153

In [26]:
import pickle
lrFile=open('LRModel.pckl','wb')
pickle.dump(pipe_lr_r13,lrFile)
lrFile.close()

In [27]:
global lrLangDetectModel
lrLangDetectFile=open('LRModel.pckl','rb')
lrLanDetectModel=pickle.load(lrLangDetectFile)
lrLangDetectFile.close()

In [28]:
def lang_detect(text):
  import numpy as np
  import string
  import re
  import pickle
  translate_table=dict((ord(char),None) for char in string.punctuation)

  global lrLangDetectModel
  lrLangDetectFile=open('LRModel.pckl','rb')
  lrLangDetectModel=pickle.load(lrLangDetectFile)
  lrLangDetectFile.close()

  text=" ".join(text.split())
  text=text.lower()
  text=re.sub(r"\d+","",text)
  text=text.translate(translate_table)
  pred=lrLangDetectModel.predict([text])
  prob=lrLangDetectModel.predict_proba([text])
  return pred[0]

In [29]:
print(lang_detect("Hello I Just built my own"))

English


In [30]:
print(lang_detect("wir sind alle auf der suche nach schnellen"))

German


In [32]:
print(lang_detect("விக்கிப்பீடியா wikipedia"))

Tamil


In [34]:
print(lang_detect("['δεν υπάρχει αυτή τη στιγμή  "))

Greek
