<a href="https://colab.research.google.com/github/SunkaraboinaPraveenKumar/Machine_Learning_Projects/blob/main/TextClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews -f 'IMDB Dataset.csv'


Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
License(s): other
IMDB%20Dataset.csv.zip: Skipping, found more recently modified local copy (use --force to force download)


In [4]:
import zipfile
import pandas as pd

# If the dataset is in a zip file, unzip it
with zipfile.ZipFile('/content/IMDB%20Dataset.csv.zip', 'r') as zip_ref:
    zip_ref.extractall('imdb_reviews')

# Load the dataset into a pandas DataFrame
df = pd.read_csv('imdb_reviews/IMDB Dataset.csv')
df=df[:10000]
# Display the first few rows to confirm
print(df.head())

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive


In [5]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [6]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [7]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [8]:
df.duplicated().sum()

17

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.duplicated().sum()

0

In [11]:
#basic preprocessing
#remove tags
#lowercase
#remove stop words

In [12]:
import re
def remove_tags(raw_text):
  cleaned_text=re.sub(re.compile('<.*?>'),'',raw_text)
  return cleaned_text

In [13]:
df['review']=df['review'].apply(remove_tags)

In [14]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [15]:
df['review']=df['review'].apply(lambda x:x.lower())

In [16]:
df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[9983 rows x 2 columns]

In [17]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [18]:
from nltk.corpus import stopwords
sw_list=stopwords.words('english')
df['review']=df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [19]:
df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [20]:
X=df.iloc[:,0:1]
Y=df['sentiment']

In [21]:
X

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [22]:
Y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [23]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
Y=encoder.fit_transform(Y)

In [24]:
Y

array([1, 1, 1, ..., 0, 0, 1])

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [26]:
X_train.shape

(7986, 1)

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
cv=CountVectorizer()

In [29]:
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

In [30]:
X_test_bow.shape

(1997, 48282)

In [31]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train_bow,Y_train)

GaussianNB()

In [32]:
GaussianNB()

GaussianNB()

In [33]:
y_pred=gnb.predict(X_test_bow)
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(Y_test,y_pred)

0.6324486730095142

In [34]:
confusion_matrix(Y_test,y_pred)

array([[717, 235],
       [499, 546]])

In [35]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train_bow,Y_train)
y_pred_rf=rf.predict(X_test_bow)
accuracy_score(Y_test,y_pred_rf)

0.8452679018527791

In [36]:
cv=CountVectorizer(max_features=3000)
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

rf=RandomForestClassifier()
rf.fit(X_train_bow,Y_train)
y_pred_rf=rf.predict(X_test_bow)
accuracy_score(Y_test,y_pred_rf)

0.828743114672008

In [37]:
cv=CountVectorizer(ngram_range=(1,3),max_features=5000)
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

rf=RandomForestClassifier()
rf.fit(X_train_bow,Y_train)
y_pred_rf=rf.predict(X_test_bow)
accuracy_score(Y_test,y_pred_rf)

0.8382573860791187

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [40]:
X_train_tfidf=tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf=tfidf.transform(X_test['review']).toarray()

In [41]:
rf=RandomForestClassifier()
rf.fit(X_train_tfidf,Y_train)
y_pred_rf=rf.predict(X_test_tfidf)
accuracy_score(Y_test,y_pred_rf)

0.8467701552328493

In [42]:
import gensim
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [45]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [46]:
story=[]
for doc in df['review']:
  raw_sent=sent_tokenize(doc)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [47]:
model=gensim.models.Word2Vec(window=10,min_count=2)

In [48]:
model.build_vocab(story)

In [50]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(5876595, 6212140)

In [51]:
len(model.wv.index_to_key)

31845

In [52]:
def document_vector(doc):
  #remove out-of-vocabulary words
  doc=[word for word in doc.split() if word in model.wv.index_to_key]
  return np.mean(model.wv[doc],axis=0)

In [54]:
document_vector(df['review'].values[0])

array([-0.21008918,  0.44755983,  0.12108903,  0.29778957, -0.10923619,
       -0.6229684 ,  0.18118533,  0.9213309 , -0.3403973 , -0.25947112,
       -0.28647572, -0.4856465 ,  0.12589504,  0.12282202,  0.15994635,
       -0.10368917,  0.04541811, -0.34510958, -0.10105081, -0.6271385 ,
        0.04691928,  0.21860932,  0.10209699, -0.2245573 , -0.3413796 ,
       -0.00615816, -0.36676553, -0.03770445, -0.30109817, -0.01302629,
        0.36053938, -0.00935527,  0.18396646, -0.26878586, -0.11855331,
        0.46568733,  0.0897292 , -0.35461798, -0.25554213, -0.81048506,
        0.11909185, -0.24639855,  0.03368784, -0.10727064,  0.5097571 ,
       -0.12457871, -0.27749243, -0.10529372,  0.15242647,  0.43093547,
        0.01889363, -0.39031672, -0.38511688, -0.12355853, -0.11031014,
        0.20822428,  0.20745818,  0.06295426, -0.30601105,  0.14873572,
        0.08963414,  0.04184053, -0.01119632, -0.0583142 , -0.41312343,
        0.18151711,  0.0271238 ,  0.08114159, -0.33046356,  0.31

In [55]:
from tqdm import tqdm

In [56]:
X=[]
for doc in tqdm(df['review'].values):
  X.append(document_vector(doc))

100%|██████████| 9983/9983 [08:24<00:00, 19.80it/s]


In [57]:
X=np.array(X)

In [58]:
X.shape

(9983, 100)

In [59]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [60]:
Y=encoder.fit_transform(df['sentiment'])

In [61]:
Y

array([1, 1, 1, ..., 0, 0, 1])

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)


In [63]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,Y_train)
y_pred=gnb.predict(X_test)
accuracy_score(Y_test,y_pred)

0.7250876314471708

In [64]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,Y_train)
y_pred_rf=rf.predict(X_test)
accuracy_score(Y_test,y_pred_rf)

0.7731597396094141